LoanApp/Models/DataBaseModel/SystemSetup.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanApp.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetup
    {
        public int SID { get; set; }
        public int Code { get; set; }
        public string Value { get; set; }
        public string Name { get; set; }
    }
}

LoanApp/Controllers/Web/SystemSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoanApp.Models.DataBaseModel;

namespace LoanApp.Controllers.Web
{
   
    public class SystemSetupController : Controller
    {
        // GET: SystemSetup
        LoanAppDBEntities db = new LoanAppDBEntities();
        public ActionResult MobileAppWellcomeScreen()
        {
            var l = db.SystemSetups.Where(x => x.Code == (int) _app.SystemSetup.MobileAppPhotos).ToList();

            return View(l);
        }


        public ActionResult ContactUsNumbers()
        {
            var u = db.SystemSetups.Where(x => x.Code == (int)_app.SystemSetup.ContactUs).ToList();

            return View(u);
        }


        [HttpPost]
        public ActionResult ContactUsNumbers(List<SystemSetup> ss)
        {

          
            var u = db.SystemSetups.Where(x => x.Code == (int)_app.SystemSetup.ContactUs).ToList();
            u.FirstOrDefault(x=> x.SID  == 4).Value = Request.Form["v_4"];
            u.FirstOrDefault(x => x.SID == 5).Value = Request.Form["v_5"];
            u.FirstOrDefault(x => x.SID == 6).Value = Request.Form["v_6"];
            db.SaveChanges();
            _app.ui.msg.Show = "تم الحفظ بنجاح";

            return RedirectToAction("ContactUsNumbers") ;
        }
    }
}

LoanApp/Views/SystemSetup/ContactUsNumbers.cshtml
@model List<LoanApp.Models.DataBaseModel.SystemSetup>

@{
    ViewBag.Title = "ContactUsNumbers";
    Layout = "~/Views/Shared/_masterLayout.cshtml";
}

<h2>ارقام التواصل لتطبيق الجوال</h2>




<div class="panel">
    <div class="panel-body">



        @using (Html.BeginForm((string)ViewBag.Contoler, "SystemSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()


            foreach (var item in Model)
            {

                <div class="mb10">
                    @Html.Label(item.Name, new { @class = "control-label" })
                    @Html.TextBox("v_" + item.SID, item.Value, new { @class = "form-control", @required = "" })
                </div>

            }


            <div class="row">
                <div class="col-md-offset-2 col-md-2">
                    <input type="submit" value="حفظ" class="btn btn-darkblue " />
                </div>
               

            </div>


        }

    </div>
</div>

LoanApp/Views/SystemSetup/MobileAppWellcomeScreen.cshtml
@model IEnumerable<LoanApp.Models.DataBaseModel.SystemSetup>

@{
    ViewBag.Title = "شاشه الترحيب بتطبيق الهاتف";
    Layout = "~/Views/Shared/_masterLayout.cshtml";
}


@foreach (var item in Model)
{

    <div class="col-md-6">

        <div class="panel panel-default panel-timeline">
            <div class="panel-heading">

                <div class="media">
                    <a href="#" class="pull-left">
                        
                    </a>
                    <div class="media-body">
                       
                    </div>
                </div><!-- media -->

            </div><!-- panel-heading -->
            <div class="panel-body">

                <div class="media">
                   
                        <a href="#" class="pull-left btn btn-success" onclick="return BtnClicked(this);" dbid="@item.SID"> 
                            تغير الصوره
                        </a>
                    
                    <div class="media-body">
                        <img  alt="" style="width:200px;height:500px" id="Photo_@item.SID" src="@item.Value" />

                    </div>
                </div>


            </div><!-- panel-body -->
            
        </div>

    </div>


}

<input type="file" id="up_photo" name="up_photo" style="display:none" />

<script type="text/javascript">


    var id = 0;
    function BtnClicked(b)

    {
        id = $(b).attr('dbid');
       
        $('#up_photo').click();
        return false;
    }


    $('#up_photo').change(function () {

        var filepath = $(this).val();
        var ext = filepath.split('.');
        var fext = ext[ext.length - 1]
        fext = fext.toLowerCase();
        if (fext == 'jpg' || fext == 'png' || fext == 'jpeg') {
            var reader = new FileReader();

            var pho = '';
            reader.readAsDataURL($(this).prop('files')[0]);
            reader.onload = function (event) {
                $('#Photo_' + id).attr('src', event.target.result);
                pho = event.target.result;
            };

            reader.onloadend = function ()
            
            {
                ShowMSg('جاري رفع الصوره ، برجاء الانتظار');

                var json = { 'dbid': id, 'Photo': pho };
                



                var url = document.location.origin + '/api/' + 'Global' + '/' + 'UploadMobileScreenPhoto';


                $.ajax({
                    url: url,
                    type: 'POST',
                    data: JSON.stringify(json),
                    contentType: "application/json;charset=utf-8",
                    success: function () {
                        ShowMSg('تم رفع الصوره بنجاح');

                    },
                    error: function () {
                        ShowMSg('فشل تحميل الملف');

                    }
                });

            }
           




           
        }
        else { alert('مسموح فقط .jpg , .png or .jpeg بتلك انواع الصور !'); $(this).val(''); }
    });


</script>