LoanApp/Models/DataBaseModel/Notification.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanApp.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NoID { get; set; }
        public string Header { get; set; }
        public string Continet { get; set; }
        public int CreatedEmp { get; set; }
        public string Photo { get; set; }
        public System.DateTime SentDate { get; set; }
        public bool ToCustomers { get; set; }
        public bool ToSalesReps { get; set; }
        public bool ToBankReps { get; set; }
        public Nullable<int> ToUser { get; set; }
        public string PageName { get; set; }
        public Nullable<int> LoanID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual UsersInfo UsersInfo { get; set; }
        public virtual LoansRequest LoansRequest { get; set; }
    }
}

LoanApp/Controllers/Web/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LoanApp.Models.DataBaseModel;
using LoanApp.Models.Classes;

namespace LoanApp.Controllers.Web
{
    public class NotificationsController : Controller
    {
        private LoanAppDBEntities db = new LoanAppDBEntities();

        // GET: Notifications
        public ActionResult Index()
        {
            var notifications = db.Notifications.Include(n => n.Employee).OrderByDescending(x=> x.SentDate).Where(x=> x.ToUser == null);
            return View(notifications.ToList());
        }


        //[AllowAnonymous]
        //public ActionResult mailTest()
        //{
        //    Send.eMail e = new Send.eMail();
        //        e.SendMail();
        //    return View();
        //}


        //// GET: Notifications/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Notification notification = db.Notifications.Find(id);
        //    if (notification == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(notification);
        //}

        // GET: Notifications/Create
        public ActionResult Create()
        {
            //  ViewBag.CreatedEmp = new SelectList(db.Employees, "EmpID", "EmpID");
            Notification n = new Notification();
            return View(n);
        }

        // POST: Notifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Notification noti)
        {
            if (ModelState.IsValid)
            {

                Notification n = new Notification();
                Send.Notifications not = new Send.Notifications();
                noti.Photo = _app.ui.photo.replacePhoto(n.Photo, Request.Files);
                noti.CreatedEmp = _app.ui.current.User.UserID;
                noti.SentDate = _app.ui.DateNow;
                noti.PageName = _app.Notifecations.NotifecationsPage();
                db.Notifications.Add(noti);
                db.SaveChanges();

              //  var ms = db.MobileSessions.Select(x => x.MobileID).Distinct();

                if (noti.ToCustomers)
                {
                    var cl = db.Customers.ToList();
                    foreach (var c in cl)
                    {
                        not.SendNotification(c.UsersInfo, noti );
                    }

                }

                if (noti.ToBankReps)
                {
                    var brl = db.BankRepresentatives.ToList();
                    foreach (var c in brl)
                    {
                        not.SendNotification(c.UsersInfo, noti);
                    }

                }

                if (noti.ToSalesReps)
                {
                    var srl = db.SalesRepresentatives.ToList();
                    foreach (var c in srl)
                    {
                        not.SendNotification(c.UsersInfo, noti);
                    }

                }


                _app.ui.msg.Show = "تم ارسال التنبيه بنجاح";
                return RedirectToAction("Index");
            }

          
            //  ViewBag.CreatedEmp = new SelectList(db.Employees, "EmpID", "EmpID", notification.CreatedEmp);
            return View(noti);
        }

        // GET: Notifications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notification notification = db.Notifications.Find(id);
            if (notification == null)
            {
                return HttpNotFound();
            }
            ViewBag.CreatedEmp = new SelectList(db.Employees, "EmpID", "EmpID", notification.CreatedEmp);
            return View(notification);
        }

        // POST: Notifications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NoID,Header,Continet,CreatedEmp,Photo,SentDate")] Notification notification)
        {
            if (ModelState.IsValid)
            {
                db.Entry(notification).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CreatedEmp = new SelectList(db.Employees, "EmpID", "EmpID", notification.CreatedEmp);
            return View(notification);
        }

        // GET: Notifications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notification notification = db.Notifications.Find(id);
            if (notification == null)
            {
                return HttpNotFound();
            }
            return View(notification);
        }

        // POST: Notifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Notification notification = db.Notifications.Find(id);
            db.Notifications.Remove(notification);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LoanApp/Views/Notifications/Create.cshtml
@model LoanApp.Models.DataBaseModel.Notification

@{
    ViewBag.Title = "تنبيه جديد";
    Layout = "~/Views/Shared/_masterLayout.cshtml";
}

<link href="~/Theme/css/bootstrap-wysihtml5.css" rel="stylesheet" />
<script src="~/Theme/js/wysihtml5-0.3.0.min.js"></script>
<script src="~/Theme/js/bootstrap-wysihtml5.js"></script>


<div class="panel">
    <div class="panel-body">




        @using (Html.BeginForm((string)ViewBag.Contoler, "Notifications", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="col-md-8">

                <div class="form-horizontal">


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="mb10">
                        @Html.LabelFor(x => x.Header, "العنوان", new { @class = "control-label" })
                        @Html.TextBoxFor(x => x.Header, new { @class = "form-control", @required = "" })
                    </div>

                    <div class="mb10">
                        @Html.LabelFor(x => x.Continet, "المحتوي", new { @class = "control-label" })

                        @*@Html.TextBoxFor(x => x.Continet, new { @class = "wysiwyg", @required = "", class="form-control" rows="10" })*@
                        @Html.TextAreaFor(x => x.Continet, new { @class = "wysiwyg form-control", @required = "", rows = "10", @style = "text-align:right" })
                    </div>


                    <div class="row">
                        <div class="mb10">
                            <div class="col-md-1"></div>
                            <div class="col-md-2">
                                <div class="mb10">
                                    @Html.CheckBoxFor(x => x.ToCustomers, new { @onchange = "cbChanged()", @checked = "checked" })
                                    @Html.LabelFor(x => x.ToCustomers, "العملاء", new { @class = "control-label" })

                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="mb10">
                                    @Html.CheckBoxFor(x => x.ToSalesReps, new { @onchange = "cbChanged()" })
                                    @Html.LabelFor(x => x.ToSalesReps, "المندوبين", new { @class = "control-label" })

                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="mb10">
                                    @Html.CheckBoxFor(x => x.ToBankReps, new { @onchange = "cbChanged()" })
                                    @Html.LabelFor(x => x.ToBankReps, "مندوبين البنوك", new { @class = "control-label" })

                                </div>
                            </div>

                        </div>

                    </div>







                </div>


            </div>

            <div class=" col-md-1"></div>
            <div class="col-md-2 text-center">

                <div class="row"><br /> </div>
                <div class="row"><br /></div>
                <div class="row">
                    <img id="Photo" alt="" style="width:200px;height:200px" src="@Model.Photo" />

                </div>
                <div class="row">
                    <input type="file" id="up_photo" name="up_photo" />
                    <br />
                    <hr />
                </div>
                <div class="row">
                    <input type="button" value="مسح الصوره" class="btn btn-danger" onclick="removePhoto()" />
                </div>
            </div>


            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-offset-2 col-md-2">
                        <input type="submit" value="ارسال التنبيه" class="btn btn-darkblue " id="btn_submit" disabled="disabled" />
                    </div>
                    <div class="col-md-2">
                        @Html.ActionLink("عوده", "Index", null, new { @class = "btn btn-orange" })
                    </div>
                </div>
            </div>
        }

        <script type="text/javascript">

            $(document).ready(function () {

                $('.wysiwyg').wysihtml5({
                    color: false, html: false,
                    "link": false,
                    "image": false
                });


                //    $('#Photo').hide();


            });


            $('#up_photo').change(function () {

                var filepath = $(this).val();
                var ext = filepath.split('.');
                var fext = ext[ext.length - 1]
                fext = fext.toLowerCase();
                if (fext == 'jpg' || fext == 'png' || fext == 'jpeg') {
                    var reader = new FileReader();

                    reader.readAsDataURL($(this).prop('files')[0]);
                    reader.onload = function (event) {
                        $('#Photo').attr('src', event.target.result);
                    };
                    $('#Photo').show();
                }
                else { alert('مسموح فقط .jpg , .png or .jpeg بتلك انواع الصور !'); $(this).val(''); }
            });

            function removePhoto() {
                $('#Photo').attr('src', '');
                $('#up_photo').val('');
                $('#Photo').hide();
            }


            function cbChanged() {
                // alert($(cb).is(':checked'));
                var i = 0;

                if ($('#ToCustomers').is(':checked')) { i += 1; }
                if ($('#ToSalesReps').is(':checked')) { i += 1; }
                if ($('#ToBankReps').is(':checked')) { i += 1; }

                if (i > 0) { $('#btn_submit').val(' ارسال التنبيه (' + i + ')'); $('#btn_submit').removeAttr('disabled'); }
                else { $('#btn_submit').attr('disabled', 'disabled'); $('#btn_submit').val('ارسال التنبيه'); }

            }

        </script>
    </div>
</div>

LoanApp/Views/Notifications/Index.cshtml
@model IEnumerable<LoanApp.Models.DataBaseModel.Notification>

@{
    ViewBag.Title = "التنبيهات";
    Layout = "~/Views/Shared/_masterLayout.cshtml";
}


<p>
    @Html.ActionLink("تنبيه جديد !", "Create", null, new { @class = "btn btn-black" })
</p>


<div class="panel">
    <div class="panel-body">


        @foreach (var item in Model)
        {

            <div class="col-md-6">

                <div class="panel panel-default panel-timeline">
                    <div class="panel-heading">

                        <div class="media">
                            <a href="#" class="pull-left">
                                <img alt="" src="@item.Employee.UsersInfo.Photo" class="media-object">
                            </a>
                            <div class="media-body">
                                <h4 class="text-primary">@item.Employee.UsersInfo.FullName</h4>
                                <small class="text-muted">@item.SentDate.ToShortDateString() , @item.SentDate.ToLongTimeString()</small>
                            </div>
                        </div><!-- media -->

                    </div><!-- panel-heading -->
                    <div class="panel-body">

                        <div class="media">
                            @if (item.Photo != null)
                            {
                                <a href="#" class="pull-left">
                                    <img alt="" src="@item.Photo" class="media-object">
                                </a>
                            }
                            <div class="media-body">
                                <h4><a href="">@item.Header </a></h4>
                                @Html.Raw(@item.Continet)

                            </div>
                        </div>


                    </div><!-- panel-body -->
                    <div class="panel-footer">
                        <div class="media">
                            <a href="#" class="pull-left">

                            </a>
                            <div class="media-body">

                                <div class="row">

                                    @if (item.ToCustomers == true)
                                    {
                                        <div class="col-md-4">
                                            <div class="checkbox block">
                                                <label>
                                                    <input type="checkbox" checked="" disabled="">
                                                    العملاء
                                                </label>
                                            </div>
                                        </div>
                                    }

                                    @if (item.ToSalesReps == true)
                                    {
                                        <div class="col-md-4">
                                            <div class="checkbox block">
                                                <label>
                                                    <input type="checkbox" checked="" disabled="">
                                                    المندوبين
                                                </label>
                                            </div>
                                        </div>
                                    }

                                    @if (item.ToBankReps == true)
                                    {
                                        <div class="col-md-4">
                                            <div class="checkbox block">
                                                <label>
                                                    <input type="checkbox" checked="" disabled="">
                                                    مندوبين البنوك
                                                </label>
                                            </div>
                                        </div>
                                    }

                                </div>
                            </div>
                        </div><!-- media -->
                    </div>
                </div>

            </div>


        }
    </div>
</div>

LoanApp/Views/Notifications/Test.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

LoanApp/Views/Notifications/mailTest.cshtml
@{
    ViewBag.Title = "mailTest";
    Layout = "~/Views/Shared/_masterLayout.cshtml";
}

<h2>mailTest</h2>