LoanApp/Models/DataBaseModel/Branch.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanApp.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.BankRepresentatives = new HashSet<BankRepresentative>();
            this.Employees = new HashSet<Employee>();
            this.LoansRequests = new HashSet<LoansRequest>();
            this.CustomerSelectionLoans = new HashSet<LoansRequest>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public int BranchCode { get; set; }
        public bool Active { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<int> BranchMangerEmpID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankRepresentative> BankRepresentatives { get; set; }
        public virtual Employee Manger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoansRequest> LoansRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoansRequest> CustomerSelectionLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}

LoanApp/Controllers/Web/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoanApp.Models.DataBaseModel;
using System.Net;

namespace LoanApp.Controllers
{
    public class BranchController : Controller
    {
        private LoanAppDBEntities db = new LoanAppDBEntities();
        // GET: Branch
        public ActionResult Index()
        {
            return View(db.Branchs.ToList());
        }

        // GET: Branch/Details/5
        public ActionResult Details(int id)
        {
            #pragma warning disable CS0472 // The result of the expression is always the same since a value of this type is never equal to 'null'
            if (id == null)
            #pragma warning restore CS0472 // The result of the expression is always the same since a value of this type is never equal to 'null'
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var br = db.Branchs.Find(id);
            if (br == null)
            {
                return HttpNotFound();
            }


            return View(br);
        }

        // GET: Branch/Create
        public ActionResult Create()

        {
            Branch b = new Branch();
            //var emps = db.Employees.Where(x => db.Branchs.Any(y => x.EmpID != y.BranchMangerUserID)).ToList();
            //ViewBag.BranchMangerUserID = new SelectList(emps, "EmpID", "FullName", null) ;
            return View(b);
        }

        // POST: Branch/Create
        [HttpPost]
        public ActionResult Create(Branch b)
        {
            try
            {
                
                b.lat = Request.Form["gmap0-t"];
                b.lng = Request.Form["gmap0-g"];
                b.Active = true;

                db.Branchs.Add(b);
                db.SaveChanges();


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Branch/Edit/5
        public ActionResult Edit(int id)
        {
            var b = db.Branchs.Find(id);
            var emps = db.Employees.Where(x => x.BranchID == id ).ToList();
            //if (b.BranchMangerUserID != null) {
            //     emps.Add(b.BranchManger.Employee);
            //}

            var q = from x in emps select new  { EmpID = x.EmpID, FullName = x.UsersInfo.FullName };
            ViewBag.BranchMangerUserID = new SelectList(q, "EmpID", "FullName", b.BranchMangerEmpID );
            return View(b);
        }

        // POST: Branch/Edit/5
        [HttpPost]
        public ActionResult Edit(Branch br)
        {
            try
            {
                // TODO: Add update logic here

                var oldBr = db.Branchs.Find(br.BranchID);
                oldBr.BranchName = br.BranchName;
                oldBr.Active = br.Active;
                oldBr.lat = Request.Form["gmap"+ br.BranchID.ToString()+"-t"];
                oldBr.lng = Request.Form["gmap" + br.BranchID.ToString() + "-g"];
                oldBr.BranchCode = br.BranchCode;
                oldBr.BranchMangerEmpID = br.BranchMangerEmpID;
                db.Entry(oldBr).State = System.Data.Entity.EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Branch/Delete/5
        public ActionResult Delete(int id)
        {
            var br = db.Branchs.Find(id);
            return View(br);
        }

        // POST: Branch/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed (int id)
        {
            try
            {
                // TODO: Add delete logic here
                var b = db.Branchs.Find(id);
                db.Branchs.Remove(b);

                db.SaveChanges();



                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LoanApp/Views/Branch/Create.cshtml
@model LoanApp.Models.DataBaseModel.Branch


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MasterBranches.cshtml";
}

<h2>فرع جديد</h2>

<div class="panel">
    <div class="panel-body">



        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()


            <div class="col-md-11 ">






                <div class=" col-md-10">

                    <div class="mb10">



                        @Html.HiddenFor(x => x.BranchID)



                        <div class=" mb10">
                            @Html.LabelFor(x => x.BranchName, "الاسم الفرع", new { @class = "control-label" })
                            @Html.TextBoxFor(x => x.BranchName, new { @class = "form-control", @placeholder = "اسم الفرع", @required = "" })

                        </div>
                        <div class=" mb10">
                            @Html.LabelFor(x => x.BranchCode, "كود الفرع", new { @class = "control-label" })
                            @Html.TextBoxFor(x => x.BranchCode, new { @class = "form-control", @placeholder = "كود الفرع", @required = "" })
                        </div>



                    </div>




                    <div class="row">

                        <div class="mb10">
                            @Html.Partial("~/Views/Shared/_gMap.cshtml", new LoanApp.Models.DataBaseModel.gLocation()
                       {
                           lid = Model.BranchID.ToString(),
                           lat = Model.lat,
                           log = Model.lng,
                           readOnly = false
                       })
                        </div>


                    </div>
                </div>
                <div class="row">

                </div>


                <div class="row">
                    <div class="col-md-offset-2 col-md-2">

                        <input type="submit" value="حفظ" class="btn btn-darkblue " />
                    </div>
                    <div class="col-md-2">
                        @Html.ActionLink("عوده", "Index", null, new { @class = "btn btn-orange" })
                    </div>

                </div>



            </div>

        }
    </div>
</div>

LoanApp/Views/Branch/Delete.cshtml
@model LoanApp.Models.DataBaseModel.Branch


@{
                /**/



                ViewBag.Title = "Delete";
                Layout = "~/Views/Shared/_MasterBranches.cshtml";
                var active = "";
                if (Model != null)
                {
                    if (Model.Active) { active = "checked"; }
                    else { active = ""; }

                }
                else { active = "checked"; }
}
}

<h2>حذف</h2>


<div class="panel">
    <div class="panel-body">



        @using (Html.BeginForm())
        {
            <h3>هل انت متاكد من حذف بنك @</h3>
            <div class="col-md-11 col-lg-offset-1">



                <div class=" col-md-10">

                    <div class="mb10">
                        <label class="control-label">أسم الفرع</label>
                        <span class="info">@</span>
                    </div>

                    <div class="mb10">
                        <label class="control-label">كود الفرع</label>
                        <span class="info">@</span>
                    </div>



                    <div class="row">

                        <div class="col-md-7">
                            @Html.Partial("~/Views/Shared/_gMap.cshtml", new LoanApp.Models.DataBaseModel.gLocation()
                   {
                       lid = Model.BranchID.ToString(),
                       lat = Model.lat,
                       log = Model.lng,
                       readOnly = true
                   })
                        </div>


                    </div>
                </div>




                @

                <div class="row"></div>

                <div class="row">
                    <div class="col-md-offset-2 col-md-2">


                        @if (_app.model.branchCanBeDelete(Model))
                        {

                            <input type="submit" value="حذف" class="btn btn-danger " />
                        }
                        else
                        {
                            <div class="row">
                                <input type="submit" value="حذف" class="btn btn-danger " disabled />
                            </div>
                            <div class="row">
                                <span class="infosummary">غير مسموج بمسح هذا الفرع لوجود حركات بأسمه في قاعده البيانات</span>
                            </div>



                        }
                    </div>
                    <div class="col-md-2">
                        @
                    </div>
                    <div class="col-md-2">
                        @
                    </div>



                </div>
            </div>
        }
    </div>
</div>

LoanApp/Views/Branch/Details.cshtml
@model LoanApp.Models.DataBaseModel.Branch
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MasterBranches.cshtml";
}

<h2>بيانات فرع : @Model.BranchName </h2>

<div class="panel">
    <div class="panel-body">



        <div class="col-md-11 ">






            <div class=" col-md-10">

                <div class="mb10">
                    <label class="control-label">أسم الفرع</label>
                    <span class="info">@Model.BranchName</span>

                </div>

                <div class="mb10">
                    <label class="control-label">كود الفرع</label>
                    <span class="info">@Model.BranchCode</span>
                </div>


                <div class="mb10">
                    <label class="control-label">مدير الفرع</label>
                    @if (Model.BranchMangerUserID != null)
                    {
                        <a href="@Url.Action("Details", "Employe", new { id = Model.BranchMangerUserID })">
                            <span class="info">
                                @Model.BranchManger.FullName
                            </span>
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("Edit", "Branch", new { id = Model.BranchID })">
                            <span class="info text-danger">
                                غير محدد
                            </span>
                        </a>
                    }
                </div>

                <div class="row">

                    <div class="col-md-7">
                        @Html.Partial("~/Views/Shared/_gMap.cshtml", new LoanApp.Models.DataBaseModel.gLocation() { lid = Model.BranchID.ToString(),lat = Model.lat ,
                   log = Model.lng, readOnly = true })
                    </div>
                </div>
            </div>
            <div class="row">

            </div>
            <div class="row">
                <div class="col-md-offset-2 col-md-2">
                    @Html.ActionLink("تعديل بيانات", "Edit", new { id = Model.BranchID },
                   new { @class = "btn btn-brown" })

                </div>
                <div class="col-md-2">
                    @Html.ActionLink("عوده", "Index", null, new { @class = "btn btn-orange" })
                </div>

            </div>



        </div>



        <br />
        <br />


        <div class="row ">
            <div class="col-md-10">
                @Html.Partial("~/views/Shared/_LoanRequest.cshtml", Model.LoansRequests.ToList())
            </div>
        </div>
    </div>
</div>

LoanApp/Views/Branch/Edit.cshtml
@model LoanApp.Models.DataBaseModel.Branch

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MasterBranches.cshtml";
    var active = "";
    if (Model != null)
    {
        if (Model.Active) { active = "checked"; }
        else { active = ""; }

    }
    else { active = "checked"; }
}

<h2>تعديل بيانات فرع :@Model.BranchName</h2>


<div class="panel">
    <div class="panel-body">


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()


            <div class="col-md-11 ">






                <div class=" col-md-10">

                    <div class="mb10">



                        @Html.HiddenFor(x => x.BranchID)



                        <div class=" mb10">
                            @Html.LabelFor(x => x.BranchName, "اسم الفرع", new { @class = "control-label" })
                            @Html.TextBoxFor(x => x.BranchName, new { @class = "form-control", @placeholder = "الاسم البنك", @required = "" })

                        </div>
                        <label class="control-label">الكود</label>
                        <div class=" mb10">
                            @Html.LabelFor(x => x.BranchCode, "كود الفرع", new { @class = "control-label" })
                            @Html.TextBoxFor(x => x.BranchCode, new { @class = "form-control", @placeholder = "كود الفرع", @required = "" })
                        </div>




                        <div class="mb10">
                            <label class="control-label">مدير الفرع</label>

                            @Html.DropDownList("BranchMangerUserID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.BranchMangerUserID, "", new { @class = "text-danger" })

                        </div>

                        <div class="mb10">
                            <label class="control-label">حاله الفرع</label>

                            <div class="">





                                <label class="checkbox-inline">
                                    @Html.CheckBoxFor(x => x.Active, new
                               {
                                   active,
                                   @data_toggle = "toggle",
                                   @data_on = "يقبل التحويلات",
                                   @data_off = "لا يبقل التحويلات"
                               })

                                </label>

                            </div>

                        </div>



                    </div>




                    <div class="row">

                        <div class="mb10">
                            @Html.Partial("~/Views/Shared/_gMap.cshtml", new LoanApp.Models.DataBaseModel.gLocation()
                   {
                       lid = Model.BranchID.ToString(),
                       lat = Model.lat,
                       log = Model.lng,
                       readOnly = false
                   })
                        </div>


                    </div>
                </div>



                <div class="row">

                </div>


                <div class="row">
                    <div class="col-md-offset-2 col-md-2">

                        <input type="submit" value="حفظ" class="btn btn-darkblue " />
                    </div>
                    <div class="col-md-2">
                        @Html.ActionLink("عوده", "Index", null, new { @class = "btn btn-orange" })
                    </div>

                </div>



            </div>

        }

    </div>
</div>

LoanApp/Views/Branch/Index.cshtml
@model List<LoanApp.Models.DataBaseModel.Branch>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MasterBranches.cshtml";
}

<h2>الفروع</h2>


<div class="panel">
    <div class="panel-body">



        <p>
            @Html.ActionLink("اضافه فرع جديد", "Create", null, new { @class = "btn btn-black" })
        </p>


        <div id="bloglist" class="row" style="position: relative; height: 885.516px;">



            @foreach (var item in Model)
            {
                <div class="col-xs-6 col-sm-4 col-md-3" @*style="position: absolute; left: 0px; top: 0px;"*@>
                    <div class="blog-item">
                        <div class="blog-img">
                            @Html.Partial("~/Views/Shared/_gMap.cshtml", new LoanApp.Models.DataBaseModel.gLocation() { lid = item.BranchID.ToString()
                           ,lat = item.lat, log = item.lng, readOnly =true })
                        </div>
                        <div class="blog-details">
                            <div class="blog-title row">
                                <div class="pull-left">
                                    <h4>
                                        @Html.ActionLink(item.BranchName, "Details", new { id = item.BranchID })
                                    </h4>
                                </div>
                                <div class=" pull-right">
                                    <h4>
                                        @item.BranchCode
                                    </h4>
                                </div>
                            </div>


                            <ul class="blog-meta">
                                <li>الموظفين @item.Employees.Count موظف</li>
                                <li>العقود @item.LoansRequests.Count</li>
                                <li><a href="">@item.LoansRequests.Where(x => x.LoanStatus.StatusID == 2 || x.LoanStatus.StatusID == 8).ToList().Count عقود مرفوضه</a></li>
                            </ul>
                            <div class="blog-summary">


                                <div class="row text-center">
                                    <div class="col-md-4">
                                        <a href="@Url.Action("Details", new { id = item.BranchID.ToString() })" title="الصفحه الاساسيه"><i class="fa fa-info"></i></a>
                                    </div>

                                    <div class="col-md-4">
                                        <a href="@Url.Action("Edit", new { id = item.BranchID.ToString() })" title="تعديل بيانات"><i class="fa fa-pencil"></i></a>
                                    </div>

                                    <div class="col-md-4">
                                        <a href="@Url.Action("Delete", new { id = item.BranchID.ToString() })" class="delete-row danger aRed" title="حذف المدينه"><i class="fa fa-trash-o"></i></a>
                                    </div>

                                </div>
                                <div class="row text-center">

                                    @if (item.Active)
                                    {<span class="info">يقبل التحويلات</span> }
                                    else
                                    { <span class="aRed">لا يقبل التحويلات</span>}


                                </div>


                            </div>
                        </div>
                    </div><!-- blog-item -->
                </div>

            }

            <!-- col-xs-6 -->






        </div>



    </div>
</div>