LoanApp/Models/DataBaseModel/Receipt.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanApp.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ReceiptID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int CreateEmpID { get; set; }
        public int SalesRepID { get; set; }
        public int BranchID { get; set; }
        public int EmpID { get; set; }
        public decimal Amount { get; set; }
        public string AccountFrom { get; set; }
        public string AccountTo { get; set; }
        public string BankToName { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee CreatedEmployee { get; set; }
        public virtual SalesRepresentative SalesRepresentative { get; set; }
        public virtual Branch Branch { get; set; }
    }
}

LoanApp/Controllers/Web/LoanRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoanApp.Models.DataBaseModel;
using System.Net;

namespace LoanApp.Controllers
{
    [WebPagesAuthorize]
    public class LoanRequestController : Controller
    {

        LoanAppDBEntities db = new LoanAppDBEntities();


        private IEnumerable<LoansRequest> Lrl
        { get
            {
               // var l = db.LoansRequests.OrderByDescending(x => x.RequestDate);
                var u = _app.ui.current.User;
                // if (u.Employee.BranchID == 1) { return l; }
                //  else { return l.Where(x => x.BranchID == u.Employee.BranchID); }
                return u.Employee.MyLoanRequest.OrderByDescending(x => x.RequestDate);
            }
        }

        private int LoansPerPage = 5;

        // GET: LoanRequest
        public ActionResult Index()
        {

            // var l = db.LoansRequests.ToList().OrderByDescending(x => x.RequestDate);
            return View(Lrl.Take(LoansPerPage).ToList());
        }

        // GET: LoanRequest/Details/5
        public ActionResult Details(int id)
        {
            var b = db.LoansRequests.Find(id);
            //  var c = b.Commitments.ToList()[0];

            //  ViewBag.RepID = new SelectList(db.BankRepresentatives, "UserID", "FullName");
            return View(b);
        }



        // GET: LoanRequest/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LoanRequest/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LoanRequest/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LoanRequest/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }




        public ActionResult Accepted()
        {
            return View(Lrl.Where(x => x.StatusID == 1).Take(LoansPerPage).ToList());
        }
        public ActionResult DeclinedByApp()
        {
            return View(Lrl.Where(x => x.StatusID == 2).Take(LoansPerPage).ToList());
        }
        public ActionResult inCompelete()
        {
            return View(Lrl.Where(x => x.StatusID == 3).Take(LoansPerPage).ToList());
        }
        public ActionResult Sent2Branch()
        {
            var u = _app.ui.current.User;

            if (u.Employee.BranchID == 1)
            { return View(Lrl.Where(x => x.StatusID == 4).Take(LoansPerPage).ToList()); }
            else
            {
                return View(Lrl.Where(x => x.BranchID == u.Employee.BranchID && x.StatusID == 4).Take(LoansPerPage).ToList());
            }

        }
        public ActionResult Sent2Bank()
        {
            return View(Lrl.Where(x => x.StatusID == 5).Take(LoansPerPage).ToList());
        }
        public ActionResult ReceivedFromBank()
        {
            return View(Lrl.Where(x => x.StatusID == 6).Take(LoansPerPage).ToList());
        }
        public ActionResult Compeleted()
        {
            return View(Lrl.Where(x => x.StatusID == 7).Take(LoansPerPage).ToList());
        }
        public ActionResult DeclinedByEmp()
        {
            return View(Lrl.Where(x => x.StatusID == 8).Take(LoansPerPage).ToList());
        }
        public ActionResult AccedptedAndFinished()
        {
            return View(Lrl.Where(x => x.StatusID == 9).Take(LoansPerPage).ToList());
        }
        public ActionResult DeclineLoanByBranch()
        {
            return View(Lrl.Where(x => x.StatusID == 10).Take(LoansPerPage).ToList());
        }
        public ActionResult UnConfirmedLoans()
        {

            return View(Lrl.Where(x => x.StatusID == 0).Take(LoansPerPage).ToList());
        }
        public ActionResult Archive()
        {
            return View(Lrl.Where(x => x.StatusID == 8 || x.StatusID ==9 || x.StatusID == 10 ).Take(LoansPerPage).ToList());
        }

       


        [HttpPost]
        public ActionResult ScroolHandler(WebAdo.LoansScrool ls)
        {

            if (ls.MaxLoanID == 0) { ls.MaxLoanID = db.LoansRequests.Max(x => x.LoanID) + 1; }

            List<LoansRequest> l = new List<LoansRequest>();


            if (ls.Status == 4 && _app.ui.current.User.Employee.BranchID != 1)
            { l = Lrl.Where(x => x.BranchID == _app.ui.current.User.Employee.BranchID && x.StatusID == ls.Status && x.LoanID < ls.MaxLoanID).Take(LoansPerPage).ToList(); }

            if (ls.Status == 8910) {

                l = Lrl.Where(x => x.StatusID == 8 || x.StatusID == 9 || x.StatusID == 10).Take(LoansPerPage).ToList();
                if (_app.ui.current.User.Employee.BranchID != 1) {
                    l = l.Where(x => x.BranchID == _app.ui.current.User.Employee.BranchID).ToList();
                }
            }

            else if (ls.Status > 0)
            { l = Lrl.Where(x => x.StatusID == ls.Status && x.LoanID < ls.MaxLoanID).Take(LoansPerPage).ToList(); }

            else
            { l = Lrl.Where(x => x.LoanID < ls.MaxLoanID).Take(LoansPerPage).ToList(); }
             


            if (l.Count > 0) { return PartialView("~/Views/Shared/_LoanRequestScroolLoader.cshtml", l); }
            else { return null; }
 
            
            





            //return View();
        }

    }
}

LoanApp/Controllers/Web/ReceiptController.cs
using LoanApp.Models.DataBaseModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rotativa;

namespace LoanApp.Controllers
{
    public class ReceiptController : Controller
    {
        private LoanAppDBEntities db = new LoanAppDBEntities();
        // GET: Receipt
        public ActionResult Index()
        {
            var rec = db.Receipts.ToList();
            return View(rec);
        }

        // GET: Receipt/Details/5
        public ActionResult Details(int id)

        {

            ViewBag.formMode = "Details";
            var r = db.Receipts.Find(id);
            if (r == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }

            return View(r);
        }

        // GET: Receipt/Create
        public ActionResult Create()
        {

            var qsr = from sp in db.SalesRepresentatives.ToList() select new { sp.UsersInfo.UserID, sp.UsersInfo.FullName };
            ViewBag.SalesRepID = new SelectList(qsr.ToList(), "UserID", "FullName");

            ViewBag.BranchID = new SelectList(db.Branchs, "BranchID", "BranchName");

            var qemp = from em in db.Employees.ToList() select new { em.UsersInfo.FullName, em.UsersInfo.UserID };
            ViewBag.EmpID = new SelectList(qemp, "UserID", "FullName");
            var emp = db.Employees.Find(_app.ui.current.User.UserID);
            Receipt r = new Receipt();
            r.CreatedEmployee = emp;
            ViewBag.formMode = "Create";
            return View(r);


            ;
        }

        // POST: Receipt/Create
        [HttpPost]
        public ActionResult Create(Receipt re)
        {
            //try
            //{
            // TODO: Add insert logic here

            re.CreateEmpID = _app.ui.current.User.UserID;
            re.DateAdded = _app.ui.DateNow;
            db.Receipts.Add(re);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = re.ReceiptID });
            //}
            //catch
            //{
            //    return View();
            //}
        }



        // GET: Receipt/Delete/5
        public ActionResult Delete(int id)
        {
            var r = db.Receipts.Find(id);
            if (r == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            ViewBag.formMode = "Details";
            return View(r);
        }

        // POST: Receipt/Delete/5
       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed (int id)
        {
            try
            {

                var r = db.Receipts.Find(id);
                db.Receipts.Remove(r);
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
        public ActionResult Print(int id)
        {
            
            return new ActionAsPdf("PrintRecepit", new { id = id }) { FileName="PDF_File.pdf" } ;
        }
        [AllowAnonymous]
        public ActionResult PrintRecepit(int id)
        {
            ViewBag.formMode = "Details";
            var r = db.Receipts.Find(id);
            if (r == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            return View(r);
           
        }
    }
}

LoanApp/Views/Shared/_LoanRequest.cshtml
@model List<LoanApp.Models.DataBaseModel.LoansRequest>






<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <!-- panel-btns -->
            <h3 class="panel-title">العقود</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    @if (Model.Count > 0) { 
                    <table class="table ">
                        <thead>
                            <tr>
                                <td>رقم الطلب</td>
                                <th>تاريخ الطلب</th>
                                <th>الوقت</th>
                                <th>اسم العميل</th>
                                <th>الراتب الشهري</th>
                                @*<th>المبلغ المطلوب</th>*@
                                <th>البنك</th>
                                <th>حاله الطلب</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.ActionLink(item.LoanID.ToString(),"Details","LoanRequest",
                                       new { id= item.LoanID },null )</td>
                                    <td>@item.RequestDate.ToShortDateString() </td>
                                     <td>@item.RequestDate.ToShortTimeString() </td>
                                    <td>@item.Customer.UsersInfo.FullName</td>
                                    <td>@item.Salary ر.س</td>
                                    @*<td>@item.Funds  ر.س</td>*@
                                    <td>@item.Bank.BankName</td>
                                    <td>@item.LoanStatus.StatusName</td>

                                </tr>
                            }
                        </tbody>

                    </table>
                    }
                    else {<h4>لايوجد عقود  في قاعده البيانات</h4> }
                </div>
            </div>
        </div>
    </div>
</div>

LoanApp/Views/Shared/_LoanRequestActions.cshtml
@model LoanApp.Models.DataBaseModel.LoansRequest


@if (_app.ui.current.User.Employee.BranchID == 1)
{

    if (Model.StatusID == 0)
    { <a class="btn btn-brown-alt" href="#">طلب تجريبي</a> }
    if (Model.StatusID == 1)
    { <a class="btn btn-darkblue" href="@Url.Action("MoveToBranch", "LoanActions", new { id = Model.LoanID })">تحويل للفرع</a>
    <hr />
    <a class="btn btn-danger" href="@Url.Action("AcceptOrDeclineLoan", "LoanActions", new { id = Model.LoanID })">رفض</a>
    }
    if (Model.StatusID == 2)
    { <a class="btn btn-danger" href="@Url.Action("AcceptOrDeclineLoan", "LoanActions", new { id = Model.LoanID })">رفض</a> }

    if (Model.StatusID == 3)
    { <a class="btn btn-brown-alt" href="#">مندوب غير متكمل</a> }
    if (Model.StatusID == 4)
    {<hr /> <a class="btn btn-black" href="@Url.Action("MoveToBank", "LoanActions", new { id = Model.LoanID })">تحويل للبتك</a>
        <hr />
    <a class="btn btn-danger" href="@Url.Action("DeclineLoanByBranch", "LoanActions", new { id = Model.LoanID })">رفض الطلب</a> }
    if (Model.StatusID == 5)
    { <a class="btn btn-brown" href="@Url.Action("AddBankData", "LoanActions", new { id = Model.LoanID })">استيفاء البيانات</a> }
    if (Model.StatusID == 6)
    { <a class="btn btn-danger" href="@Url.Action("AddLoanFundData", "LoanActions", new { id = Model.LoanID })">تحويل للفرع الرئيسي</a>
        <hr />
    <a class="btn btn-danger" href="@Url.Action("DeclineLoanByBranch", "LoanActions", new { id = Model.LoanID })">رفض الطلب</a> }
    if (Model.StatusID == 7)
    { <a class="btn btn-default" href="@Url.Action("AcceptOrDeclineLoan", "LoanActions", new { id = Model.LoanID })">قبول</a> }
    if (Model.StatusID == 10)
    { <a class="btn btn-danger" href="@Url.Action("AcceptOrDeclineLoan", "LoanActions", new { id = Model.LoanID })">رفض</a> }

    if(_app.LoanReq.CanBeTransferdToBranchEmp().Any(z=> z == Model.StatusID))
    {<hr/> <a class="btn btn-default" href="@Url.Action("EmpTransfer", "LoanActions", new { id = Model.LoanID })">تحويل لموظف اخر</a>}

}

else
{


    if (Model.StatusID == 4)
    {<hr /> <a class="btn btn-black" href="@Url.Action("MoveToBank", "LoanActions", new { id = Model.LoanID })">تحويل للبتك</a>
        <hr />
        <a class="btn btn-danger" href="@Url.Action("DeclineLoanByBranch", "LoanActions", new { id = Model.LoanID })">رفض الطلب</a> }
    if (Model.StatusID == 5)
    { <a class="btn btn-brown" href="@Url.Action("AddBankData", "LoanActions", new { id = Model.LoanID })">استيفاء البيانات</a> }
   if (Model.StatusID == 6)
    { <a class="btn btn-danger" href="@Url.Action("AddLoanFundData", "LoanActions", new { id = Model.LoanID })">تحويل للفرع الرئيسي</a>
        <hr />
        <a class="btn btn-danger" href="@Url.Action("DeclineLoanByBranch", "LoanActions", new { id = Model.LoanID })">رفض الطلب</a> }
   



}

LoanApp/Views/Shared/_LoanRequestEditMenu.cshtml
@model LoanApp.Models.DataBaseModel.LoansRequest



@if (_app.ui.current.User.Employee.BranchID == 1)
{



if (!_app.LoanReq.CanBeEditedStatus().Contains(Model.StatusID))
{
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-10">
            <a href="@Url.Action("Details", "LoanRequest", new { id = Model.LoanID })" class="pull-right"
               title="عرض تفاصيل العقد" data-placement="right" data-toggle="tooltip">
                <h3>
                    <span class="glyphicon glyphicon-info-sign"></span>
                </h3>
            </a>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group mr5" title="خيارات" data-placement="right" data-toggle="tooltip">
                <button type="button" class="btn btn-default-alt dropdown-toggle pull-right" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-wrench"></span>
                </button>
                <ul class="dropdown-menu pull-left" role="menu">
                    <li>

                        <a href="@Url.Action("Details", new { id = Model.LoanID })">
                            <span class="glyphicon glyphicon-info-sign"></span>
                            عرض تفاصيل العقد
                        </a>

                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="@Url.Action("Edit", "Customers", new { id = Model.CustomerID })">
                            <span class="glyphicon glyphicon-user"></span>
                            تعديل بيانات العميل

                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Edit", "LoanActions", new { id = Model.LoanID })">
                            <span class="glyphicon  glyphicon-list-alt"></span>

                            تعديل بيانات الطلب
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("index", "Commitments", new { id = Model.LoanID })">
                            <span class="glyphicon  glyphicon-align-right"></span>
                            تعديل التزامات الطلب
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
}
}
else
{
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-10">
            <a href="@Url.Action("Details", "LoanRequest", new { id = Model.LoanID })" class="pull-right"
               title="عرض تفاصيل العقد" data-placement="right" data-toggle="tooltip">
                <h3>
                    <span class="glyphicon glyphicon-info-sign"></span>
                </h3>
            </a>
        </div>
    </div>

}

LoanApp/Views/Shared/_LoanRequestInfoBubble.cshtml
@model LoanApp.Models.DataBaseModel.LoansRequest



<div class="col-md-12">
    <div class="people-item">
        <div class="media">
            <a href="#" class="pull-left">
                <img alt="" src="@Model.Customer.UsersInfo.Photo" class="thumbnail media-object">
            </a>
            <div class="media-body">
                <h4 class="person-name">
                <a href="@Url.Action("Details","Customers", new { id= Model.CustomerID })">
                @Model.Customer.UsersInfo.FullName</a>
                </h4>

                <div class="col-md-6">
                    <div class="text-muted">
                        <i></i>
                        رقم الهويه :@Model.Customer.NationalID
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="text-muted">رقم الطلب :@Model.LoanID</div>
                </div>
                <div class="col-md-6">
                    <div class="text-muted">
                        المدينه :
                        @if (Model.Customer.City != null)
                        { @Model.Customer.City.CityName }
                        else
                        { <text> <span class="aRed">غير محدد</span> </text> }
                    </div>
                </div>
                <div class="col-md-6">
                   
                        <div class="text-muted">تاريخ الطلب :@Model.RequestDate.ToShortTimeString()</div>
                   
                </div>
                <div class="col-md-6">
                    <div class="text-muted">
                        الوظيفه :
                        @if (Model.Customer.Job != null)
                        { @Model.Customer.Job.JobName }
                        else
                        { <text> <span class="aRed">غير محدد</span> </text> }
                    </div>
                </div>
                <div class="col-md-6">
                    
                        <div class="text-muted">الحالة الحاليه :@Model.LoanStatus.StatusName</div>
                   
                </div>
                <div class="col-md-6">

                    <div class="text-muted">عدد لالتزامات :@Model.Commitments.Count</div>

                </div>
                <div class="col-md-6">

                    <div class="text-muted">مجموع الالتزامات :@Model.CommitmentsTotal ر.س</div>

                </div>

                         
                
            </div>
        </div>
        
    </div>
</div>

LoanApp/Views/Shared/_LoanRequestScroolLoader.cshtml
@model IEnumerable<LoanApp.Models.DataBaseModel.LoansRequest>




@foreach (var item in Model)
{
    <div class="col-md-6">
        @Html.Partial("~/Views/Shared/_LoanRequestThumbnail.cshtml", item)
    </div>
}

LoanApp/Views/Shared/_MasterBranches.cshtml
@{

    Layout = "~/Views/Shared/_masterLayout.cshtml";

}




        @RenderBody()

LoanApp/Views/Shared/_MenuHeaderAndItems.cshtml
@model LoanApp.Models.DataBaseModel.MenuHeader



@if (Model.MenuItems.Count > 0)
{

    <li class="nav-parent">
        <a href=""><i class="@Model.HeaderIcon"></i> <span>@Model.HeaderName</span></a>
        <ul class="children">

            @foreach (var item in Model.MenuItems)
            {
                <li><a href="@Url.Action(item.Action,item.Controller)"><i class="@item.ItemIcon"></i>@item.ItemName</a></li>
            }

        </ul>
    </li>

}

LoanApp/Views/Shared/_PrintingLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>



    @System.Web.Optimization.Styles.Render("~/Content/Css")


    <script src="http://maps.google.com/maps/api/js?key=AIzaSyCBQfj2fF2BjD2EF1ajCVHNf27LCUXpuwE&language=ar"></script>
    @System.Web.Optimization.Scripts.Render("~/Content/Js")

</head>
<body>
    <div>
        @RenderBody()

    </div>
</body>
</html>

LoanApp/Views/Shared/_ReceiptsTable.cshtml
@model IEnumerable<LoanApp.Models.DataBaseModel.Receipt>
@{ decimal t1 = 0; }




@if (Model.Count() > 0)
{

    <table class="table dataTable">
        <thead>
            <tr>
                <th>#</th>
                <th>التاريخ</th>
                <th>الساعه</th>
                <th>المندوب</th>
                <th>الفرع</th>
                <th>الموظف</th>
                <th>المبلغ</th>
                <th>خيارات</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ReceiptID</td>
                    <td>@item.DateAdded.ToShortDateString()</td>
                    <td>@item.DateAdded.ToShortTimeString()</td>
                    <td>@item.SalesRepresentative.UsersInfo.FullName</td>
                    <td>@item.Branch.BranchName</td>
                    <td>@item.Employee.UsersInfo.FullName</td>
                    <td>@item.Amount ر.س</td>
                    <td>
                        <div class="row">
                            <div class="col-md-6">
                                <a href="@Url.Action("Details", "Receipt", new { id = item.ReceiptID })" title="عرض المحتوي"><i class="fa fa-info"></i></a>
                            </div>

                            <div class="col-md-6">
                                <a href="@Url.Action("Delete", "Receipt", new { id = item.ReceiptID })" class="delete-row danger aRed" title="حذف "><i class="fa fa-trash-o"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
                { t1 += item.Amount;}
            }
        </tbody>
        <tfoot>
            <tr>
                <th>الاجمالي :</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                
                <th>@t1 ر.س</th>
                <th></th>
            </tr>
        </tfoot>
    </table>

}

else
{

    <h2>لايوجد اي اذونات في قاعده البيانات</h2>
}

LoanApp/Views/Shared/_UserMenuUpdate.cshtml
@model LoanApp.Models.DataBaseModel.UsersInfo




@{


    var enabled = "";

    if (ViewBag.formMode == "edit" || ViewBag.formMode == "create")
    {
        enabled = "";

    } else if(ViewBag.formMode == "details") { enabled = "disabled"; }
   
}








@if (Model.Employee != null ||  ViewBag.AccountType == "Emp")
{
    <div class="col-md-12">
        <h3>الصلاحيات</h3>


       

        @foreach (var item in _app.ui.current.AllMenuHeaders())
                {

            <div class="col-md-3">


                @if (Model.MenuHeaders == null)
                {<input type="checkbox" id="mh_@item.HeaderID" name="mh_@item.HeaderID" @enabled /> }

                else if (Model.MenuHeaders.Any(x => x.HeaderID == item.HeaderID))
                { <input type="checkbox" id="mh_@item.HeaderID" name="mh_@item.HeaderID" checked="checked" @enabled /> }
                else
                { <input type="checkbox" id="mh_@item.HeaderID" name="mh_@item.HeaderID" @enabled /> }

                

               


                <label class="control-label" for="mh_@item.HeaderID">@item.HeaderName</label>

            </div>

        }
    </div>
}

LoanApp/Views/Shared/_gMap.cshtml
@model  LoanApp.Models.DataBaseModel.gLocation





<div id="@Model.lid" style="height: 300px; position: relative; overflow: hidden;">
    
</div>

<input id="pac-input"  type="text" class="form-control " style="width:300px"  placeholder="بحث عن مكان">

<script type="text/javascript">


    var marker;
    $(document).ready(function () {

        $('#@Model.lid-t').val(@Model.lat);
         $('#@Model.lid-g').val(@Model.log);

        var t =  $('#@Model.lid-t').val();
        var g =  $('#@Model.lid-g').val();

        var ro =  '@Model.readOnly';

        if (ro == 'False') { ro = false; } else { ro = true; };
        if (t == 0) {  t = 24.708178400790256; };
        if (g== 0) { g = 46.677721687500025; };

        var myLatlng = new google.maps.LatLng(t, g);
        var mapOptions = {
            zoom: 6,
            center: myLatlng,
            draggable: !ro,
            disableDefaultUI: ro
        }

        var @Model.lid = new google.maps.Map(document.getElementById("@Model.lid"), mapOptions);

        var map = @Model.lid;
        marker = new google.maps.Marker({
            position: myLatlng,
            draggable: !ro,
            animation: google.maps.Animation.DROP,




        });


        marker.setMap( map);


        addMarkerListener(marker);



        if (ro == false) {





            var input = document.getElementById('pac-input');
            var searchBox = new google.maps.places.SearchBox(input);
            map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

            // Bias the SearchBox results towards current map's viewport.
            map.addListener('bounds_changed', function () {
                searchBox.setBounds(map.getBounds());
            });

            var markers = [];
            // Listen for the event fired when the user selects a prediction and retrieve
            // more details for that place.
            searchBox.addListener('places_changed', function () {
                var places = searchBox.getPlaces();
                marker.setMap(null);
                if (places.length == 0) {
                    return;
                }

                // Clear out the old markers.
                markers.forEach(function (marker) {
                    marker.setMap(null);
                });
                markers = [];
                var bounds = new google.maps.LatLngBounds();
                // For each place, get the icon, name and location.
                var i = 0;
                places.forEach(function (place) {


                    // Create a marker for each place.
                    markers.push(new google.maps.Marker({
                        map: map,
                        draggable: !ro,
                        title: place.name,
                        position: place.geometry.location
                    }));

                    addMarkerListener(markers[i]);
                    i += 1;
                    if (place.geometry.viewport) {
                        // Only geocodes have viewport.
                        bounds.union(place.geometry.viewport);
                    } else {
                        bounds.extend(place.geometry.location);
                    }

                });
                map.fitBounds(bounds);

            });



        }

        else { $("#pac-input").remove(); }





    });

    $(document).ready(function () {
        $(window).keydown(function (event) {
            if (event.keyCode == 13) {
                event.preventDefault();
                return false;
            }
        });
    });



    function addMarkerListener(marker) {
          google.maps.event.addListener(marker, 'dragend', function () {


            $('#@Model.lid-t').val(marker.getPosition().lat());
            $('#@Model.lid-g').val(marker.getPosition().lng());






        });

    }


</script>

<input type="hidden" id="@Model.lid-t" name="@Model.lid-t" value="0" />
<input type="hidden" id="@Model.lid-g" name="@Model.lid-g" value="0" />

LoanApp/Views/Shared/_masterLoanActionLayout.cshtml
@{ 

    Layout = "~/Views/Shared/_masterLayout.cshtml";

}






<script type="text/javascript">


    $(document).ready(function () {
        $('[name="actionlink"]').hide();


    });

</script>

        @RenderBody()
  